name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false # never use caching in release builds
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

      - name: Type check
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --access public
